#include <stdio.h>
#include <stdlib.h>

// Converts a binary file into a C source file with an embedded byte array.
// Usage: bin2c <input> <output.c> <varprefix>
// Emits:  const unsigned char <varprefix>_bytes[] = {...};
//         const size_t <varprefix>_bytes_len = N;
int main(int argc, char **argv)
{
    if (argc != 4)
    {
        fprintf(stderr, "usage: %s <input> <output.c> <varprefix>\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "rb");
    if (!in)
    {
        perror(argv[1]);
        return 1;
    }
    FILE *out = fopen(argv[2], "w");
    if (!out)
    {
        perror(argv[2]);
        fclose(in);
        return 1;
    }

    fprintf(out, "/* Generated by bin2c from %s — do not edit. */\n", argv[1]);
    fprintf(out, "#include <stddef.h>\n");
    fprintf(out, "const unsigned char %s_bytes[] = {\n", argv[3]);

    unsigned char buf[16];
    size_t n;
    size_t total = 0;
    while ((n = fread(buf, 1, sizeof(buf), in)) > 0)
    {
        fprintf(out, "    ");
        for (size_t i = 0; i < n; i++)
        {
            fprintf(out, "0x%02x,", buf[i]);
        }
        fprintf(out, "\n");
        total += n;
    }
    fprintf(out, "};\n");
    fprintf(out, "const size_t %s_bytes_len = %zu;\n", argv[3], total);

    fclose(in);
    fclose(out);
    return 0;
}
